server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  # database ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kjdatabase
    username: root
    password:

    # spring data jpa ??
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update

#### log
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ???? ????.

#file:
#  path: /Users/junghunmok/springupload/

